version: '3'
services:
  ai:
    container_name: emotions-app
    restart: always
    build: 
      context: ./ai
      dockerfile: ./Dockerfile
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8000:80"
    networks:
      app-network:
        ipv4_address: 192.168.1.5 
  web:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    ports:
      - "80:80"
    networks:
      app-network:
        ipv4_address: 192.168.1.4

networks:
  app-network:
    external: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1