version: '3'
services:
  app:
    container_name: emotions-app
    restart: always
    build: .
    working_dir: /app
    ports:
      - 80:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]