name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
            
      # - name: Run Black
      #   run: |
      #     pip install black
      #     black . 
      # - uses: iterative/setup-dvc@v1
      # - name: Set up DVC credentials
      #   env:
      #     DVC_CREDENTIALS_FILE: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      #   run: |
      #     echo "GDRIVE_CREDENTIALS_DATA" > /tmp/dvc_credentials.txt
      #     export DVC_USER_ID=$(awk -F '=' '/user_id/ {print $2}' /tmp/dvc_credentials.txt)
      #     export DVC_SECRET_KEY=$(awk -F '=' '/secret_key/ {print $2}' /tmp/dvc_credentials.txt)
      
      # - name: Install SSH key
      #   run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

      - name: Deploy code
        run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ubuntu@3.91.2.203 "git pull origin main"

      - name: Set up DVC
        run: |
          pip install dvc dvc-gdrive
          dvc remote modify myremote secret $DVC_SECRET_KEY


      - name: Pull data from DVC
        run: |
          dvc pull -r myremote 



      - name: Install dependencies
        run: |
        
          pip install -r ./ai/requirements.txt
          pip install -r ./web/requirements.txt

  
      - name: Run tests
        run: pytest

      - name: cleanup
        run: rm -rf ~/.ssh

      