name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Configure DVC
        run: |
          ip addr
          pip install dvc dvc-gdrive
          dvc pull ai/models

      - name: Install dependencies
        run: |
        
          pip install -r ./ai/requirements.txt
          pip install -r ./web/requirements.txt

  
      - name: Run tests
        working-directory: ./ai
        run: pytest

      