name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
            
      # - name: Run Black
      #   run: |
      #     pip install black
      #     black . --check --diff

      - uses: iterative/setup-dvc@v1
      - name: Set up DVC credentials
        env:
          DVC_CREDENTIALS_FILE: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          echo "GDRIVE_CREDENTIALS_DATA" > /tmp/dvc_credentials.txt
          export DVC_USER_ID=$(awk -F '=' '/user_id/ {print $2}' /tmp/dvc_credentials.txt)
          export DVC_SECRET_KEY=$(awk -F '=' '/secret_key/ {print $2}' /tmp/dvc_credentials.txt)

      - name: Set up DVC
        run: |
          pip install dvc dvc-gdrive
          dvc remote modify myremote user $DVC_USER_ID
          dvc remote modify myremote secret $DVC_SECRET_KEY

      - name: Pull data from DVC
        run: |
          dvc pull -r myremote 



      - name: Install dependencies
        run: |
        
          pip install -r ./ai/requirements.txt
          pip install -r ./web/requirements.txt

  
      - name: Run tests
        run: pytest

      